
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-3
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOB74XIA","is_bot":false,"login":"brOlivares","name":"Bryan Olivares"},"headRefName":"Bryan-StorkeImage","number":38,"title":"Frontend: Added storke image to AppNavbar","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/38"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"RidePut","number":37,"title":"RideRequest PUT endpoint","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/37"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"RideDelete","number":36,"title":"RideRequest Delete endpoint","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/36"},{"author":{"id":"MDQ6VXNlcjg2NTQ4MjY0","is_bot":false,"login":"dingfan123","name":"Dingfan Zheng"},"headRefName":"Dingfan-replace-email","number":35,"title":"Dingfan replace email","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/35"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"RideGetPost","number":30,"title":"Added GET and POST requests ","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/30"},{"author":{"id":"MDQ6VXNlcjcyODI1MTY5","is_bot":false,"login":"Firoc","name":"Jason Vu"},"headRefName":"jason-toggle-button","number":27,"title":"Jason - Toggle Button Front End","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/27"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"DriverRiderRoles","number":23,"title":"Added additional roles to SecurityConfig","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/23"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"Ivan-ShiftCRUD","number":20,"title":"Added backend for Driver Shifts","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/20"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"Ivan-RideReqCRUD","number":13,"title":"Added CRUD backend for ride requests","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/13"}]
