
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-3
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"DriverShiftDB","number":32,"title":"Added database for Driver Shifts","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/32"},{"author":{"id":"MDQ6VXNlcjcyODI1MTY5","is_bot":false,"login":"Firoc","name":"Jason Vu"},"headRefName":"jason-toggle-button","number":27,"title":"Jason - Toggle Button Front End","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/27"},{"author":{"id":"MDQ6VXNlcjg2NTQ4MjY0","is_bot":false,"login":"dingfan123","name":"Dingfan Zheng"},"headRefName":"Dingfan-colored-navbar","number":26,"title":"Dingfan colored navbar","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/26"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"RideRequestDB","number":24,"title":"Added DB for ride requests","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/24"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"DriverRiderRoles","number":23,"title":"Added additional roles to SecurityConfig","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/23"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"Ivan-ShiftCRUD","number":20,"title":"Added backend for Driver Shifts","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/20"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"Ivan-RideReqCRUD","number":13,"title":"Added CRUD backend for ride requests","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/13"}]
